[package]
name = "empl"
version = "0.1.0"
edition = "2024"

[dependencies]
bumpalo = { version = "3.17.0", default-features = false, features = ["collections"] }
crossterm = { version = "0.29.0", default-features = false, features = ["windows"] }
dirs = { version = "6.0.0", default-features = false }
enum-iterator = { version = "2.1.0", default-features = false }
enum-map = { version = "2.7.3", default-features = false }
nonempty-collections = { version = "0.3.0", default-features = false }
tokio = { version = "1.45.0", default-features = false, features = ["io-util"] }
