[package]
name = "empl"
version = "0.1.0"
edition = "2024"

[dependencies]
bumpalo = { version = "3.17.0", default-features = false, features = ["collections"] }
crossterm = { version = "0.29.0", default-features = false, features = ["windows"] }
dirs = { version = "6.0.0", default-features = false }
nonempty-collections = { version = "0.3.0", default-features = false }
