[target.aarch64-unknown-linux-musl]
passthrough = ["PKG_CONFIG_PATH"]
pre-build = [
          "dpkg --add-architecture arm64",
          "apt-get update",
          "apt-get install libasound2-dev:arm64 --yes",
]
[target.x86_64-unknown-linux-musl]
passthrough = ["PKG_CONFIG_PATH"]
pre-build = [
          "dpkg --add-architecture amd64",
          "apt-get update",
          "apt-get install libasound2-dev:amd64 --yes",
]