name: Hosted release build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin
          - aarch64-pc-windows-msvc
          - i686-pc-windows-msvc
          - x86_64-pc-windows-msvc
        include:
          - target: aarch64-apple-darwin
            host: macos-latest
          - target: x86_64-apple-darwin
            host: macos-latest

          - target: aarch64-pc-windows-msvc
            host: windows-latest
            executable-suffix: .exe
          - target: i686-pc-windows-msvc
            host: windows-latest
            executable-suffix: .exe
          - target: x86_64-pc-windows-msvc
            host: windows-latest
            executable-suffix: .exe
    runs-on: ${{matrix.host}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          rustup target add ${{matrix.target}}
          cargo build --bin empl --locked --release --target ${{matrix.target}} --verbose
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: empl-${{matrix.target}}
          path: ./target/${{matrix.target}}/release/empl${{matrix.executable-suffix}}
