name: Build release

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [aarch64, x86_64]
        os: [macos-latest, ubuntu-22.04, windows-latest]
        include:
          - os: macos-latest
            target-suffix: apple-darwin
          - os: ubuntu-latest
            target-suffix: unknown-linux-musl
          - os: windows-latest
            target-suffix: pc-windows-msvc
    runs-on: ${{matrix.os}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get upgrade --yes
          sudo apt-get install libasound2-dev --yes
          sudo apt-get install libasound2-dev:arm64 --yes
      - name: build
        run: |
          rustup target add ${{matrix.arch}}-${{matrix.target-suffix}}
          cargo build --locked --release --target ${{matrix.arch}}-${{matrix.target-suffix}}

# jobs:
#   build:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [macos-latest, ubuntu-latest, windows-latest]
#         include:
#         - os: macos-latest
#           target: macos-x86_64
#           path-prefix: ./target/release/
#           path-suffix: ''
#         - os: ubuntu-latest
#           target: linux-x86_64
#           path-prefix: ./target/release/
#           path-suffix: ''
#         - os: windows-latest
#           target: windows-x86_64
#           path-prefix: .\target\release\
#           path-suffix: .exe

#     steps:
#       - uses: actions/checkout@v4

#       - name: Linux dependencies
#         if: runner.os == 'Linux'
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y libasound2-dev

#       - name: Build
#         run: |
#           cargo build --release

#       - name: Prepare artifacts
#         run: |
#           mkdir dist
#           mv ${{ matrix.path-prefix }}empl${{ matrix.path-suffix }} dist
#           mv ${{ matrix.path-prefix }}repl${{ matrix.path-suffix }} dist

#       - name: Upload artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: ${{ matrix.target }}
#           path: dist/*
#           if-no-files-found: error
