name: Release build cross compiled

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - arm-unknown-linux-gnueabihf
          - powerpc64le-unknown-linux-gnu
        include:
          - target: x86_64-unknown-linux-gnu
            triple: x86_64-linux-gnu/
          - target: aarch64-unknown-linux-gnu
            triple: aarch64-linux-gnu/
          - target: arm-unknown-linux-gnueabihf
            triple: arm-linux-gnueabihf/
          - target: powerpc64le-unknown-linux-gnu
            triple: powerpc64le-linux-gnu/
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        env:
          PKG_CONFIG_PATH: /usr/lib/${{matrix.triple}}pkgconfig
          RUSTFLAGS: -C link-arg=-L/usr/lib/${{matrix.triple}}
        uses: houseabsolute/actions-rust-cross@v1
        with:
          force-use-cross: true
          target: ${{matrix.target}}
          args: --locked --release --bin empl
          strip: true
