name: Build debug

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev
    - name: Check formatting
      run: cargo fmt --check --verbose
    - name: Check lints
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
