name: Build release

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [aarch64, x86_64]
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - arch: aarch64
            os: ubuntu-latest
            rustflags: '-C linker=aarch64-linux-gnu-gcc'
          - os: macos-latest
            target-suffix: apple-darwin
          - os: ubuntu-latest
            target-suffix: unknown-linux-musl
          - os: windows-latest
            target-suffix: pc-windows-msvc
            executable-suffix: '.exe'
    runs-on: ${{matrix.os}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: linux aarch64 install dependencies
        if: runner.os == 'Linux' && matrix.arch == 'aarch64'
        run: |
          set +e

          UBUNTU_CODENAME="$(lsb_release -sc)"

          cat <<EOF | sudo tee /etc/apt/sources.list
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports $UBUNTU_CODENAME main universe multiverse restricted
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports $UBUNTU_CODENAME-updates main universe multiverse restricted
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports $UBUNTU_CODENAME-security main universe multiverse restricted
          EOF

          sudo dpkg --add-architecture arm64
          sudo apt update
          sudo apt install libasound2-dev:arm64 gcc-aarch64-linux-gnu --yes
      - name: linux x86_64 install dependencies
        if: runner.os == 'Linux' && matrix.arch == 'x86_64'
        run: |
          sudo apt update
          sudo apt install libasound2-dev --yes
      - name: build
        env:
          PKG_CONFIG_SYSROOT_DIR_aarch64-unknown-linux-gnu: '/usr/lib/aarch64-linux-gnu'
          PKG_CONFIG_PATH: '/usr/lib/aarch64-linux-gnu/pkgconfig'
          RUSTFLAGS: ${{matrix.rustflags}}
        run: |
          rustup target add ${{matrix.arch}}-${{matrix.target-suffix}}
          cargo build --bin empl --locked --release --target ${{matrix.arch}}-${{matrix.target-suffix}} --verbose
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: empl-${{matrix.arch}}-${{matrix.target-suffix}}
          path: ./target/${{matrix.arch}}-${{matrix.target-suffix}}/release/empl${{matrix.executable-suffix}}
