name: Build release

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [aarch64, x86_64]
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - arch: aarch64
            dpkg-target: arm64
            ubuntu-repo: https://ports.ubuntu.com/ubuntu-ports
          - arch: x86_64
            dpkg-target: amd64
            ubuntu-repo: https://archive.ubuntu.com/ubuntu
          - os: macos-latest
            target-suffix: apple-darwin
          - os: ubuntu-latest
            target-suffix: unknown-linux-gnu
          - os: windows-latest
            target-suffix: pc-windows-msvc
    runs-on: ${{matrix.os}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: linux install dependencies
        if: runner.os == 'Linux'
        run: |
          set +e

          UBUNTU_CODENAME="$(lsb_release -sc)"

          cat <<EOF | sudo tee /etc/apt/sources.list
          deb [arch=${{matrix.dpkg-target}}] ${{matrix.ubuntu-repo}} $UBUNTU_CODENAME main universe multiverse restricted
          deb [arch=${{matrix.dpkg-target}}] ${{matrix.ubuntu-repo}} $UBUNTU_CODENAME-updates main universe multiverse restricted
          deb [arch=${{matrix.dpkg-target}}] ${{matrix.ubuntu-repo}} $UBUNTU_CODENAME-security main universe multiverse restricted
          EOF

          sudo dpkg --add-architecture ${{matrix.dpkg-target}}
          sudo apt update
          sudo apt install libasound2-dev:${{matrix.dpkg-target}} --yes

          find /usr/lib
      - name: build
        env:
          PKG_CONFIG_SYSROOT_DIR_aarch64-unknown-linux-gnu: "/usr/lib/aarch64-linux-gnu"
        run: |
          rustup target add ${{matrix.arch}}-${{matrix.target-suffix}}
          cargo build --locked --release --target ${{matrix.arch}}-${{matrix.target-suffix}}

# jobs:
#   build:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [macos-latest, ubuntu-latest, windows-latest]
#         include:
#         - os: macos-latest
#           target: macos-x86_64
#           path-prefix: ./target/release/
#           path-suffix: ''
#         - os: ubuntu-latest
#           target: linux-x86_64
#           path-prefix: ./target/release/
#           path-suffix: ''
#         - os: windows-latest
#           target: windows-x86_64
#           path-prefix: .\target\release\
#           path-suffix: .exe

#     steps:
#       - uses: actions/checkout@v4

#       - name: Linux dependencies
#         if: runner.os == 'Linux'
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y libasound2-dev

#       - name: Build
#         run: |
#           cargo build --release

#       - name: Prepare artifacts
#         run: |
#           mkdir dist
#           mv ${{ matrix.path-prefix }}empl${{ matrix.path-suffix }} dist
#           mv ${{ matrix.path-prefix }}repl${{ matrix.path-suffix }} dist

#       - name: Upload artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: ${{ matrix.target }}
#           path: dist/*
#           if-no-files-found: error
