on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        cargo_arguments:
          - build
          - test
          - fmt --check
          - clippy --no-deps -- -Dwarnings
        hosts: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{matrix.hosts}}
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo
        run: cargo ${{matrix.cargo_arguments}}
