on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        host: [ubuntu-latest, windows-latest]
        cargo-arguments:
          - build
          - fmt --check
          - clippy --no-deps
          - miri test
          - test
        include:
          - cargo-arguments: fmt --check
            skip-dependencies: true
          - cargo-arguments: miri test
            rustup-component: true
            nightly: true

    runs-on: ${{matrix.host}}
    steps:
      - uses: actions/checkout@v4
      - uses: amitie10g/install-package@v1
        if: ${{ ! matrix.skip-dependencies }}
        with:
          apt: guile-3.0-dev libclang-dev
          # choco: graphviz less
          pacman: guile clang
      - name: Install nightly toolchain
        if: ${{matrix.nightly}}
        run: rustup toolchain install nightly --profile minimal && rustup default nightly
      - name: Install rustup component
        if: ${{matrix.rustup-component}}
        shell: bash
        run: rustup component add `echo ${{matrix.cargo-arguments}} | awk '{ print $1; }'`
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo
        env:
          RUSTFLAGS: -D warnings
          RUSTDOCFLAGS: -D warnings
        run: cargo ${{matrix.cargo-arguments}}
