name: Libre os release build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl          
          - x86_64-unknown-freebsd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cargo install cross
          cross build --target ${{matrix.target}} --locked --release
