name: Libre os release build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: [aarch64, x86_64]
        target-suffix: [unknown-freebsd, unknown-linux-musl]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          rustup toolchain install ${{matrix.arch}}-${{matrix.target-suffix}}
